version: 1.0.{build}.{branch}
image: Visual Studio 2017
platform:
  - x86
  - x64
configuration: Release
#before_build:
#  - nuget restore NamedPipeUtility.sln
build:
  project: NamedPipeUtility.sln
  verbosity: minimal
after_build:
  - type nul > %APPVEYOR_REPO_COMMIT%.commit
  - 7z a windows.%PLATFORM%.%APPVEYOR_REPO_BRANCH%.zip %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\*\*.exe %APPVEYOR_REPO_COMMIT%.commit -x!test_*.exe
artifacts:
  - path: windows.*.zip
    name: Windows binary
before_deploy:
  - echo on
    & for /f "usebackq delims=" %%a in (`git log --pretty^=format:%%cd -n 1`) do set TIMESTAMP="%%a"
    & for /f "usebackq delims=" %%a in (`ruby -e 'require "time"^; print Time::parse^(ENV["TIMESTAMP"]^).strftime^("%%Y%%m%%d_%%H%%M%%S"^)'`) do set TIMESTAMP=%%a
deploy:
  - provider: BinTray
    username: fenrir-naru
    api_key:
      secure: 9aElrrL3YTy/8XlhblScghgwtorv/6LRNnBkvz5v3OWPoAss903yzMQ9VfsjHzMk
    subject: fenrir-naru
    repo: github
    package: Win32NamedPipeUtility
    version: $(TIMESTAMP)/$(TIMESTAMP)
    publish: true
    override: true
    explode: false
    on:
      branch: master